language: go
sudo: false
addons:
  apt:
    packages:
      - libpcap-dev
matrix:
  include:
  - go: 1.9
  - go: "1.10"
  - go: "1.10.x"
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
