language: go
sudo: false
matrix:
  include:
  - go: 1.9
  - go: 1.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic -race .
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin" -arch="amd64" -output="{{.Dir}}.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
