version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/juanwolf/toran
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run: sudo apt-get install libpcap-dev
      - run:
          name: Run tests and store them for CircleCI
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - run: bash <(curl -s https://codecov.io/bash)
